# Generated by Django 2.0 on 2021-06-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wish_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish_list',
            name='addcart_id',
        ),
    ]
