# Generated by Django 2.0 on 2021-07-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='tutor_id',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
