# Generated by Django 2.0 on 2021-07-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='course_id',
        ),
    ]
