# Generated by Django 2.0 on 2021-07-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210713_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='check_out_id',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='tutor_id',
        ),
        migrations.RemoveField(
            model_name='check_out',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='check_out',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='check_out',
            name='tutor_id',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Check_out',
        ),
    ]
